### ISSUE TITLE
We should be able to edit blog posts with a Rich Editor

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#100]
I would also like to be able to easily toggle between the rich editor and the html tags. My preference is for [TinyMCE](https://www.tinymce.com/).

**Comment by mikedamay** [comment]
@poppastring Do you know if there is a non-minified version of tinyMCE?  If not, do you still want to use it?

**Comment by Crypt32** [comment]
When I developed my own blog engine in .NET I evlauated several RTB options and ended up with [CKEditor](https://ckeditor.com/). It is free (I think, for redistribution too), with a rich ecosystem (language, plugin support) and good configuration options. It does support image uploading as well.

**Comment by pretzelfisch** [comment]
We used to have the option to flip between tinyMCE and CKEditor, is that still possible?

**Comment by poppastring** [comment]
@mikedamay 
I believe it is here:
https://cloud.tinymce.com/stable/tinymce.min.js

**Comment by mikedamay** [comment]
PR available subject to review and rebase of other PRs - feature/rich-edit

Issues arising:
1. There are 3 alternative editors: TinyMce, NicEdit, TextArea
2. To select change site.config EntryEditControl using one of the above strings and restart the app.
3. The format of EntryEditControl has changed from the legacy app.  Not sure about our attitude to backward compatibility.
4. I managed without signing up to tinyMce.  I assume others won't have a problem as the we are treading the same path as the legacy app.
5. i cannot see that the tinyMce code plugin has any effect on the .core app or the legacy app.
