### ISSUE TITLE
Site Title - TagHelper

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#11]
A TagHelper that pulls the blog title from the site configuration file. The TagHelper should be useable from any page and would be in the following format (can use dependency injection to get info from [ISitConfig.cs](https://github.com/poppastring/dasblog-core/blob/master/source/DasBlog.Web.UI.Core/Configuration/ISiteConfig.cs):

`<sitetitle></sitetitle>`

Which would produce an output like this:

`Site Name`

TagHelpers should be created in the [DasBlog.Web.UI project](https://github.com/poppastring/dasblog-core/tree/master/source/DasBlog.Web.UI) under the TagHelpers folder, I have a [blog post on authoring TagHelpers](https://www.poppastring.com/blog/CreatingTagHelpersWithCoreMVC.aspx) here. Find out about [why we use TagHelpers here](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro), and [specific steps on authoring TagHelpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring) can be found here.

_Please note that these tasks are for code newbies who are looking to make contributions to supportive open source project using ASP.NET Core MVC. Please feel free to reach out to me on [twitter](https://twitter.com/poppastring) and I will be happy to help walk you through this._

**Comment by SQL-MisterMagoo** [comment]
Hi, 

I'm just wondering, for my own learning, whether you considered a Razor Partial for this and if you did, what made a TagHelper become your choice?

This is not questioning your choice, just trying to understand more as I try to learn aspnet core.

Thanks for your time

**Comment by poppastring** [comment]
@SQL-MisterMagoo That is a good question, for me the decision came down to if I was sharing a snippet of HTML or a piece of static data.

For **Site Title** I needed to share this info in several locations like in the <header> and also probably in the page body as a H2 tag. I did not want to limit this to a specific html tag so I opted for a tag helper rather than a partial page.

**Comment by SQL-MisterMagoo** [comment]
Thanks for taking the time to reply, much appreciated.
