### ISSUE TITLE
Some Exception Swallowed.

### ISSUE THREAD

**Issue by thousandtyone** [poppastring/dasblog-core#138]
I recently took the code-base hoping to take my blog which runs on the older version of DasBlog and upgrade it to the newer version. When I built the code the first thing that caught my eye was a couple of warnings where exceptions were being swallowed and not logged:

Controllers\BlogPostController.cs(142,21): warning CS0168: The variable 'e' is declared but never used 
Controllers\BlogPostController.cs(202,21): warning CS0168: The variable 'e' is declared but never used 
Controllers\BlogPostController.cs(217,21): warning CS0168: The variable 'ex' is declared but never used 
Controllers\HomeController.cs(122,21): warning CS0168: The variable 'e' is declared but never used 

My first gut was to do a DI of the logger and then log in the catch blocks but then I wondered if this was done on purpose / if there is a reason behind this? Could it be that Blog posting exceptions would occur when I don't have permissions to write to disk (directory is read only etc.) and if I don't have permissions to write to disk I probably could not also log to disk. Is this why some of these exceptions been not been logged on purpose? If that's the case, couldn't we just ignore specific exception types (not log them) and log the others?

I can give this a quick shot and submit a PR if that helps. Is this by design or is it  fine if I address this and submit a PR?

**Comment by poppastring** [comment]
@thousandtyone This is a good issue. A PR is most welcome!

**Comment by thousandtyone** [comment]
Thanks so much for your response. Will submit a PR this weekend.

**Comment by thousandtyone** [comment]
@poppastring  PR created. Please feel free to review and do let me know if added changes are needed.

**Comment by poppastring** [comment]
@thousandtyone Thanks for this!
