### ISSUE TITLE
Improve formating in the Create post view

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#164]
- The list of Categories does not spread align correctly appears to be skewed left.
- Allow Comments, Is Public + Syndicated should be a single row.
- Modify Create button text to "Post"

**Comment by mikedamay** [comment]
claimed

**Comment by mikedamay** [comment]
@poppastring Can you be more specific on these items.

What does "skews to the right" mean.  Are you referring to horizontal allignment?

In what way do the categories "skew to the left"?  Do you want the list to go across the page, i.e. using the right hand border of the Content field as a guide to its right hand border?

If we remove the Cancel button how will users abort a blog post?

**Comment by poppastring** [comment]
@mikedamay  I think some of this got fixed when you upgraded bootstrap. I have updated the info above for what I still think is valid. I updated the public test site with a later version so that you can see this in action. Check it out here: https://www.poppastring.com/blog2
