### ISSUE TITLE
Default values on Create Post

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#165]
**Issue 1:**
The default date/time should be based on the offset defined in DasBlogSettings object. It is currently just using _DateTime.UtcNow_ and this is incorrect (see [BlogPostController.CreatePost()](https://github.com/poppastring/dasblog-core/blob/master/source/DasBlog.Web.UI/Controllers/BlogPostController.cs)).

`<DisplayTimeZoneIndex>`

**Issue 2:**
_Allow Comments_, _Is Public_, _Syndicated_ check box values should be set to true by default.

**Comment by mikedamay** [comment]
claimed
