### ISSUE TITLE
Last deleted blog post shows up in return from GetEntries()

### ISSUE THREAD

**Issue by mikedamay** [poppastring/dasblog-core#176]
Run the collection of tests BlogDataServiceTest
from 37194f052423930414507488acba4a3aefd830b5
BlogDataService_GetEntriesWithFalse_Successful/blogdataservice.GetEntries(false) returns/ 24 posts rather than 23 because it includes a deleted post (I assume the last one created by an earlier test).  This may have consequences in the real world.

**Comment by poppastring** [comment]
@mikedamay I will looking at this tonight as this does have real world implications. ,  think this is related to the way in which dasblog caches data. I believe my changes related to the Managers do not invalidate the cache (for subsequent rebuilding) after updating the list.

**Comment by mikedamay** [comment]
claimed
