### ISSUE TITLE
Comment approval does not provide feedback on approvals

### ISSUE THREAD

**Issue by mikedamay** [poppastring/dasblog-core#210]
Task
1. Reproduce - newly installed dasblog-core, Log in as admin, home page->Comment on this Post->The Architect->Approve Comment click.  The page continues to show "Approve Comment".
2. Ensure that after an approval this link shows **"Comment Approved"**.
3. Add a test to FunctionalTests/ComponentTests/BlogManagerTests.Comments.cs

**Comment by poppastring** [comment]
@mikedamay The content of the dayfeedback.xml file updates for me, it change SpamState from **NotChecked** to **NotSpam** (also the date). You are correct though we could use this as a mechanism for allowing page feed back. Maybe change that text from **Approve Comment** to **Comment Approved**.
