### ISSUE TITLE
Consider refactoring author in the PostViewModel

### ISSUE THREAD

**Issue by t3dodson** [poppastring/dasblog-core#22]
Issue #9 brought up a point that it is not obvious where meta data like twitter account can be found.

Potentially the [PostViewModel](https://github.com/poppastring/dasblog-core/blob/master/source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs) could be expanded to contain meta data directly.

An advantage would be that the view would have direct access to this data via the model. 

The current method of using dependency injection to get access to the data (`IDasBlogSettings.IMetaTags`) is a workable solution, but expanding the model could have benefits as well.

A concern for making this change is that it would affect users on the legacy dasblog from upgrading. The current mechanism would need to make changes to the security file.

**Comment by poppastring** [comment]
Rejecting this idea as it requires too many changes to basic legacy assumptions.
