### ISSUE TITLE
Comment link should position you near the comment section

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#228]
Comments currently take on the following format:
- /post/bc7a29c7-767e-43c8-a03c-2a9ffa039b73/comments

This opens the comment section but you end up at the top of the post and are forced to scroll down to the comment section. The original dasblog would put a "#commentstart" at the end of url as follows:
- /post/bc7a29c7-767e-43c8-a03c-2a9ffa039b73/comments#start

Solution should include:
- Updating the comment url as above (see DasBlogSettings.GetCommentViewUrl() )
- Add #start anchor in the Comment partial view (_CommentBlockPartial.cshtml).

**Comment by mikedamay** [comment]
claimed
