### ISSUE TITLE
Use ASP.NET Core Identity with our custom storage provider.

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#23]
We have an XML based security file that stores identity data. Some of this was enabled with fixes required for XML-RPC.

Read and apply [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers)

**Comment by chillryan** [comment]
just an FYI @poppastring, I've started working on this. I've got the classes, but haven't don't the xml integration in the UserStore class yet.

**Comment by chillryan** [comment]
just an FYI @poppastring, I've started working on this. I've got the classes, but haven't don't the xml integration in the UserStore class yet.

**Comment by poppastring** [comment]
@chillryan Excellent, this is one of the most important issues to resolve. Send me a pull request when whenever you are ready for me to check the direction (even if it is not finished). I am open to ideas here and this is one of the biggest challenges in this project.

**Comment by chillryan** [comment]
@poppastring man the aspnet identity stuff was a PIA... so much had to be implemented, will have to look at the aspnet core repo to see why all those implementations are needed. i do have a concern with the password that's stored in the xml...it may not be compatible with passwordhash that's used by aspnet  identity. but this should at least get us in the right direction. look forward to hearing your thoughts.

**Comment by poppastring** [comment]
Sorry about the delay, I have had so much on with my day job. Anyway I will start reviewing tonight!

I know you have put a lot of work into this but feel free to push back if you think this concept is overkill. 
Looking at the original implementation of security it was so straight forward:
...\dasblog-core\source\newtelligence.DasBlog.Web.Core\SiteSecurity.cs

Anyway I am going forward with what you have and reviewing it as if this is *the* solution but I am genuinely interested in your opinion here.
