### ISSUE TITLE
Contributors Guidelines Missing

### ISSUE THREAD

**Issue by lalitkale** [poppastring/dasblog-core#24]
I am interested to make contributions, however, not sure about sending PR and Unit Tests and preliminary checks need to be done. For most of the open source projects, there is a contributors guideline exists in repo. 

I am happy to send PR with basic guidelines written for the same. However, as an owner of the repo, you can suggest what needs to be included and I can send PR for the same.

PS: Also, realized maybe issue template might also be helpful for the repo.

**Comment by poppastring** [comment]
@lalitkale ,

This is a great idea, this is what I see as the important things to consider:

- Clone the poppastring/dasblog-core git repo
- Select an issue to work on or create one
- Create a unit test for your work
- Verifying your changes (should always be able to build)
- Rebase the branch
- Pushing the branch to github
- Issue a pull request

Each of these bullets should probably be a header where we explain how we expect that particular item to be accomplished (I am aware that we do not have a Unit test project and will correct that shortly).

Thanks

**Comment by poppastring** [comment]
@lalitkale The unit test project stub has been created. Thanks!

**Comment by lalitkale** [comment]
@poppastring I am working on contributing guidelines. Expect PR around Wednesday.

**Comment by mikedamay** [comment]
I started a FAQ.  A working document
https://github.com/mikedamay/dasblog-core/blob/contributor-faq/source/ContributorFAQ.md

**Comment by poppastring** [comment]
@mikedamay Yes and yes!
