### ISSUE TITLE
Create a Unit Test project

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#25]
This is bad I mean really bad ... each contribution should have a minimum of one unit test so we are off to a slow start here.

**Comment by t3dodson** [comment]
I think along with a unit test project we also need a mocking library.

With dependency injection built into .net core I think it is a necessary component to unit tests.

**Comment by t3dodson** [comment]
I think [moq](https://github.com/moq/moq4) is a possible solution which supports .net core.

**Comment by poppastring** [comment]
@t3dodson Great idea! I have closed this issue as I created the project and stubbed the basic template for methods in a new test project. Do you mind creating a new issue with the relevant info, I am not as familiar with the context of moq.

**Comment by lalitkale** [comment]
@t3dodson @poppastring How about NSubstitute instead of Moq?
