### ISSUE TITLE
Could we use the Netscepades nuget package rather than a copy of the source file?

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#261]
Not sure why we have copied the source for Netscepades rather than use [the associated nuget package](https://www.nuget.org/packages/NetEscapades.Extensions.Logging.RollingFile/). Did we need some kind of custom solution?

**Comment by poppastring** [comment]
@mikedamay Do you know why this was the case?

**Comment by mikedamay** [comment]
claimed
