### ISSUE TITLE
Site map has a multiple URL error

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#312]
1. URL for archive is incorrect (and google is complaining)

```
<url>
<loc>https://www.poppastring.com/blog/archives</loc>
<changefreq>daily</changefreq>
<priority>1.0</priority>
<lastmod>2019-07-22</lastmod>
</url>
```

Should be **/archive** (no "s")

2. There is no base category URL reference i.e. **/category** 

3. The category urls are not formatted correctly  e.g. **/category/.NET%20Core**

4. While we are here the titles of each Category on the category page are broken in the same way as above.

**Comment by poppastring** [comment]
@shanselman Do you mind if I take this one from you? I have a few hours of coding in me this week.

**Comment by shanselman** [comment]
Sure, sorry I haven't gotten back to you yet. When are you doing it? Happy
to skype and pair.

**Comment by poppastring** [comment]
@shanselman No worries, I took a few weeks off myself, just getting back in the swing. We can pair anytime this week, I am doing about an hour or so each evening of this week. I will ping you on teams with details.
