### ISSUE TITLE
Default App URL Port 5001 Causing Connection Issues

### ISSUE THREAD

**Issue by smulholland2** [poppastring/dasblog-core#329]
The solutions build normally, but I am unable to run the DasBlog.Web app with the port set to 5001. When I try to run the app the browser gives me a "This Site Can't Be Reached. Connection reset" error.

If I change the port to 44344 in site.config and the debug section of project properties with SSL enabled, everything works as expected.

**Comment by poppastring** [comment]
@smulholland2 Thanks for opening the issue, are you debugging with the IISExpress or Kestrel (DasBlog.Web.UI)?

![image](https://user-images.githubusercontent.com/8739371/66883144-cfb10e00-ef9a-11e9-97c8-075ecac9640a.png)

**Comment by smulholland2** [comment]
I was running IISExpress. I changed it to Kestrel and everything is working fine now. Thank you.

**Comment by poppastring** [comment]
@smulholland2 I just completed a pull request, you should be able to use IISExpress or Kestrel now. Thanks for letting me know about that!
