### ISSUE TITLE
social handles

### ISSUE THREAD

**Issue by peteringemann** [poppastring/dasblog-core#362]
social sharing tailing each post should be optional... either when creating the post or as a global setting

**Comment by poppastring** [comment]
Removing social sharing buttons can be accomplished via Themes templates but I have not done a very good job of documenting Theme design.

I will keep this open until I update the documentation here:
https://github.com/poppastring/dasblog-core/wiki/4.-Designing-a-theme

**Comment by poppastring** [comment]
Updated documentation...

https://github.com/poppastring/dasblog-core/wiki/5.-Tag-Helpers-&-Partial-Views#social-sharing
