### ISSUE TITLE
Date Created field on new post is a mess

### ISSUE THREAD

**Issue by peteringemann** [poppastring/dasblog-core#364]
When adding a new post or editing old post the Date Created looks like a mess.
I like puzzles so '2020-01-25T11:54:55.758' eventually I'll figure out what means but it isn't that userfriendly.

**Comment by poppastring** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/8739371/75641865-9efb0980-5c07-11ea-967a-b783d7baa64c.png)
