### ISSUE TITLE
more detailed Appearance Settings

### ISSUE THREAD

**Issue by peteringemann** [poppastring/dasblog-core#369]
The Appearance Settings section in the old dasBlog was a bit more detailed.
Like
* show comment counter
* replace spaces in Title Permalink with [drop down - default '+']
* enable Search Result Highlighting
etc...

**Comment by poppastring** [comment]
We have "URL format" section that can be changed to "Appearance Settings". Title permalink replacement is already there and we can certainly add the other two.
