### ISSUE TITLE
Feature Request: Support Google AMP layouts

### ISSUE THREAD

**Issue by mfitconsultants** [poppastring/dasblog-core#389]
possible potential feature request to support google AMP pages.

Implementation could be to utilise `/amp/` on the routing, with seperate `.amp.cshtml` layouts as an option.

Blog html code could be possibly converted using a nuget package such as;

[Html2Amp](https://www.nuget.org/packages/HtmlToAmp/)

in combination with a `TagHelper` to convert it over to AMP layout.

The ability to `turn on` amp though the settings.

**Comment by poppastring** [comment]
I am declining this one...I have a philosophical objection to google AMP. It seems to want to its own version of HTML.

I am assuming, like https, I may have no choice in the future, for now I will decline.

Thanks for the suggestions, please keep them coming :)
