### ISSUE TITLE
Missing \content\binary folder causing application to crash.

### ISSUE THREAD

**Issue by bagstac** [poppastring/dasblog-core#398]
The configuration in the startup.cs class is trying to map \content\binary off of wwwroot which does not exist and is not created when building the solution.  

It is being mapped in the following code.
app.UseStaticFiles(new StaticFileOptions()
			{
				FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, BinariesPath)),
				RequestPath = string.Format("/{0}", BinariesUrlRelativePath)
			});

I am seeing a binary folder under wwwroot but I am not sure if that is used for something else or if the folder path is a typo.  I am hosting this in Azure but I see the same issue if I run this locally.

**Comment by poppastring** [comment]
@bagstac Thanks for figuring this out, I caused this problem last week and  I was just in the process of getting to the bottom of this. Thanks a lot!!! 👍🏿

**Comment by poppastring** [comment]
This was resolved in the last pull request. Thanks!
