### ISSUE TITLE
Invalid URL from "Comments on the post" link

### ISSUE THREAD

**Issue by dsmeltz** [poppastring/dasblog-core#414]
When clicking the following link:
![image](https://user-images.githubusercontent.com/1830600/77829795-b63ff080-70fa-11ea-8186-2d05e423e348.png)
you'll get a file not found error.   It's trying to go to:
http://localhost:5001/2020/03/22/tester/comments#comments-start
if you remove comments and make it:
http://localhost:5001/2020/03/22/tester/#comments-start
It works as expected.

**Comment by poppastring** [comment]
@dsmeltz Thanks for pointing this out! a fix is on the way.

I have to admit I do a lot of work within Visual Studio IDE for git. Here is [a link that describes my process for open source contributions on GitHub using Visual Studio](https://www.poppastring.com/blog/os-github-contributions-with-visual-studio).

Here is [another post I wrote about syncing with upstream masters](https://www.poppastring.com/blog/fixing-the-upstream-url-for-a-remote-fork). This ensure you have the latest updates from the location you forked from (if you want them).

If I am honest I rarely use the command line!

I would welcome any contributions, I am also happy to answer any questions you have, just submit a PR to connect.
