### ISSUE TITLE
Questions on 301 Redirect

### ISSUE THREAD

**Issue by thousandtyone** [poppastring/dasblog-core#439]
While migrating from older DasBlog can we please provide an option to retain the URLs instead of forcing users to use the new scheme and generating 301. I am reading articles that say that permalinks cause rank loss of SEO by at least 5 to 10%. Some sites have managed to lose ranking fully just because they did 301 permanent redirects. Is it possible to give Users an Option to Retain older URL conventions that they already used?

**Comment by poppastring** [comment]
@thousandtyone We now have setting that allows you to maintain the original "blogpost.aspx" format. It is controlled by logging into your site and selecting "**Use ASPX extensions (will not 301 redirect)**".

![image](https://user-images.githubusercontent.com/8739371/89750137-ac5ece80-da98-11ea-864b-0a873a47d318.png)
 
Thanks for the suggestion. Best of luck!

**Comment by thousandtyone** [comment]
Thanks! This lets me move my blog to the new version. Apart from a basic captcha I think I have everything else I need to move my older blog to this new platform!
