### ISSUE TITLE
../blog_path/post/search view 404 not found

### ISSUE THREAD

**Issue by mklump** [poppastring/dasblog-core#445]
In this reply, I will try to again provide more details on the second issue that was found in my last write up regarding the ../blog_path/post/search view 404 not found...
For this second noted 404 error, I had the following initial conditions,
•	After having followed your build and deploy wiki guidance [https://github.com/poppastring/dasblog-core/wiki/1.-Deployment] with the Microsoft pages, I have the following buildout directory structure that should appear the same or near the same as yours in the following small .JPG:
o	 ![build_structure](https://user-images.githubusercontent.com/16783423/90047248-7a12c400-dc86-11ea-8b42-213404408677.jpg)
•	Per your suggestion, I did attempt to start new changes with a brand new theme named “Median2” per the wiki guidance found at [https://github.com/poppastring/dasblog-core/wiki/4.-Designing-a-theme] of which resulted in –
o	C:\WINDOWS\system32>cd "C:\inetpub\wwwroot\blog_new"
o	
o	C:\inetpub\wwwroot\blog_new>dir /a .\dasblog-core.exe
o	 Volume in drive C is Windows
o	 Volume Serial Number is 8E87-9353
o	
o	 Directory of C:\inetpub\wwwroot\blog_new
o	
o	07/16/2020  12:51 AM           174,592 dasblog-core.exe
o	               1 File(s)        174,592 bytes
o	               0 Dir(s)  287,318,024,192 bytes free
o	
o	C:\inetpub\wwwroot\blog_new>.\dasblog-core.exe newtheme "Median2"
o	Could not execute because the specified command or file was not found.
o	Possible reasons for this include:
o	  * You misspelled a built-in dotnet command.
o	  * You intended to execute a .NET Core program, but dotnet-newtheme does not exist.
o	  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
o	
o	C:\inetpub\wwwroot\blog_new>dasblog-core --help
o	.NET Core SDK (3.1.302)
o	Usage: dotnet [runtime-options] [path-to-application] [arguments]
o	
o	Execute a .NET Core application...blah...blah
•	The last error specified command or file not found from the output of command dasblog-core newtheme “my_next_theme” most likely lacks either additional path configuration or another coded binary or compiled assembly library is seriously lacking? Either way as a result of that last error “Not found” I gave up and went back to trying to run the original “median” pre-provided theme pack to see if I can get that working, and it did to a point...
•	The next action I took was seeing that the code given for “median” theme does provide the following code for a search box field as –
*       [search_button_code.txt](https://github.com/poppastring/dasblog-core/files/5064648/search_button_code.txt)
•	I see that in this code from ../blog_path/Themes/median/_Layout.cshtml did render this searchText box and submit button.
•	I then attempted to use this searchText box with the text “Nant” of known existing text first at http://localhost/blog_new test path, and then again at my production site http://www.[my_production_site].com/blog.
o	The form submit routed to [http://localhost/post/search], and seeing that the path ../blog_new/Views/post/Search/ test path did not exist, this produced a 404 error -
o	HTTP Error 404.0 - Not Found
o	The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
•	I again attempted to use this searchText box with the text “Nant” of known existing text for the second time at http://www.[my_production_site].com/blog -
o	The form submit routed to [http://www.[my_production_site].com/post/search], and seeing that the path ../blog/Views/post/Search/ production path did not exist, this produced a different error –
o	HTTP Error 500.0 - Internal Server Error
o	Internal Server Error
o	Detailed Error Information:
o	Module	   ManagedPipelineHandler
o	Notification	   ExecuteRequestHandler
o	Handler	   ExtensionlessUrlHandler-Integrated-4.0
o	Error Code	   0x800703e9
o	Requested URL	   http://www.[my_production_site].com:80/post/search
o	Physical Path	   [my_physical_server_share_path]\post\search
o	Logon Method	   Anonymous
o	Logon User	   Anonymous
•	All help is greatly appreciated, and I will post general info...

**Comment by poppastring** [comment]
@mklump 

I want confirm we have a common understanding of the URL structure here. Essentially with MVC only static files (in wwwroot) can be navigated to directly over HTTP. All other views need to be accessed via Controllers which are in turn defined by Routes.

So for example for my site: https://www.poppastring.com/blog/Views/post/Search/ does not exist (you cannot navigate directly to files in Views as an example). Unlike WebForms the physical file path does not necessarily match the HTTP URI.

For example I have a theme called poppastring but I cannot navigate to my files directly like this:
https://www.poppastring.com/blog/Theme/poppastring/_Layout.cshtml


The setup issue I am seeing above is that you still have references to localhost e.g. http://localhost/post/search. This will always create a 404 for public sites. Localhosts only existing on your machine for testing. It looks like you have not updated you site.config file. I have put some instructions in the previous issue for you to work through and then we can go from there.


One mistake on part is that after you create the theme you do need to still set the theme for it take effect as follows:

`dasblog-core newtheme rainbow`

`dasblog-core config theme rainbow`

**Comment by poppastring** [comment]
@mklump 

Ok, after reviewing your site I was able to see it breaking directly. Do you mind sharing what your root element is from the Site admin page? Is that http://www.site.com or http://www.site.com/blog ?

Coincidentally I have not used the search feature so in both issues it comes down to configurations I have not exercised frequently.

I I will have solution for for both soon, but it might take a day or so to get this resolved. 

I am genuinely grateful for you patient feedback.

**Comment by tomwattscom** [comment]
FYI, quick reply to this e-mail string.
Search works fine in the basic theme that uses it and my new theme. (In my fork, tested before any changes)
I did not change the URL writing site-admin setting, it is still at whatever the default was.
I manually added a new theme as a test which worked fine. While there are minor constraints such as for all practical purposes all css must be in the theme css file, there are work arounds.
I did not have any issues with my new theme, I was a little disappointed that the comment system was not very functional, but as I did not intend to use it on this site, so I removed all relevant comment tag helpers in my theme.
I will certainly try all the new changes, but it sounds like the issues noted might be edge cases based on IIS setup, or admin features/options that may not work the same way they did in old DasBlog.

Sidebar note: In development, I do not use local host, I configure my local system to think it is the primary domain for my future domain. (hosts file), overcomes lots of IIS issues.

Thanks for all your hard work!
Old DasBlog contributor, Tom Watts

**Comment by poppastring** [comment]
@mklump 

I think I have a fix for the issue, again, I am assuming what the problem is as I do not have have IIS installed anywhere. Please get the latest code and redeploy:

I would also recommend using the Site Search _TagHelper_:
`<site-search-box />`

An example new version of site search Tag helper is currently in use in Themes\**median**\_Layout.cshtml.

Check it out and feel free to ping me if anything else comes up.
