### ISSUE TITLE
Comment Section Doesn't Show Relevant Error Messages.

### ISSUE THREAD

**Issue by thousandtyone** [poppastring/dasblog-core#458]
Steps to reproduce:

1. Go to the comments section. 
2. Enter a comment with invalid Cheesy Spam Answer. OR
3. Enter a comment with invalid email format. OR
4. Enter a command with invalid captcha. 

The Code is just redirected to the comment listing page and the entire comment the user entered is lost and all his data is erased. Ideally shouldn't the user have the ability to change the answer and try again? Or the submit button shouldn't even be enabled till these are filed properly. Users filling in comments and loosing them just because they made a typo might be an issue.

Happy to fix this if this is a valid issue.

**Comment by poppastring** [comment]
@thousandtyone  Excellent idea!

**Comment by thousandtyone** [comment]
This look a little more time than needed since the code modifications were a bit more structural. Have a working fix. Need to do some more testing on this so will be pushing a PR in a day or so once all the flows are testing from a regression perspective.

**Comment by poppastring** [comment]
@thousandtyone  Thanks for taking the time to check, I look forward to the PR!

Please also note that there is UI integration testing that can be executed within Visual Studio, this includes some testing of the comment section.

**Comment by thousandtyone** [comment]
Thanks for pointing this out. I was developing on arch linux + nvim and tried to run the integration from there but looks like there are dependencies on windows. I'll switch to my windows + visual studio environment and run these once before I submit the PR so that we can be sure nothing is broken.

**Comment by thousandtyone** [comment]
I tried to get on a windows box and setup visual studio. However the same issue exist with windows setup too:

![image](https://user-images.githubusercontent.com/24845706/93924873-f6db9800-fd32-11ea-9bc1-30f1133915ff.png)

I tried to debug but the app refuses to start.

![image](https://user-images.githubusercontent.com/24845706/93924955-0fe44900-fd33-11ea-9241-ca2a88241415.png)

May have to dig a bit deeper to find out what's causing this.

Is this something known and I'm setting this up incorrectly? Or should I debug to find out what's going on with the integration tests? Right now all of them seem to fail with the same error.

**Comment by thousandtyone** [comment]
Sorry about that. Figured it out. The selenium module was missing.

`npm install selenium-standalone@latest -g`

Did the trick. Now I'm seeing some other issues that I think I might be able to debug.

**Comment by thousandtyone** [comment]
I had to jump through a few hoops. Install java and then get the selenium server. Finally looks like I am stuck with this:

![image](https://user-images.githubusercontent.com/24845706/93931651-b7b24480-fd3c-11ea-9b8d-1e1a25fae5c1.png)

I'll continue to look at this but for now I read the integration and saw that all it does is file a comment, login and then delete that comment. I'm going to run the exact same flow manually (and many other flows and submit the PR). Will circle back to getting the integrations to work in the future.

**Comment by thousandtyone** [comment]
I'm going to submit the PR. Here is the basic changes that were made. Initially if someone posted a comment and hit the submit button without filling the spam question's answer the comment was lost.

![commentolder](https://user-images.githubusercontent.com/24845706/93934515-e7634b80-fd40-11ea-8b22-642640795edf.png)

Now they will get a nice little list of errors associated with their comment so their comment isn't lost and they get an opportunity to fix their spam answer / captcha and submit again.

![commenterrors](https://user-images.githubusercontent.com/24845706/93934756-3f9a4d80-fd41-11ea-84e9-dc3da6f35e73.png)

Went ahead and did some extensive testing on this to ensure nothing is broken. Also tested all flows covered by the integration but did that manually. I'll continue to look at how I can get the integration to work. 

For now I'm going to submit this PR.

**Comment by poppastring** [comment]
Closed by PR
