### ISSUE TITLE
Automatic build output artifacts naming and release

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#459]
Currently using Azure Dev Ops to build artifacts and the name of zip is based on the build folder ([see the yaml file](https://github.com/poppastring/dasblog-core/blob/main/azure-pipelines.yml)). 

I would like the name of the build artifacts to based on a specific format that I can easily use as part of the release i.e.:
`DasBlog.Core_2.11.(Build.BuildId).zip`

Could we also [create a draft release](https://github.com/poppastring/dasblog-core/releases) with the zip included?

**Comment by phatcher** [comment]
One other suggestion is going towards semantic versioning using something like [GitVersion,](https://gitversion.net/docs/) this can provide automatic version numbering based on the commit.  Nice thing is you also get a sensible version number for branch builds allowing for beta/draft releases.

You can then use the version for automatic tagging of the repository if the build is successful.
