### ISSUE TITLE
Invalid Object Graph Info

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#461]
The following meta tags are specified using 'name' instead of 'property' and will be ignored unless specified using the 'property' key: og:url, og:title, og:image, og:description, og:video, og:type

Replace **name** with **property**... 
`<meta name="og:url" content="" />`
`<meta name="og:title" content="" />`
`<meta name="og:image" content="" />`
`<meta name="og:description" content="" />`
`<meta name="og:video" content="" />`
`<meta name="og:type" content="blog" />`

Also **blog** is not a valid content type for og:type, and should be replaced with **website**.
`<meta property="og:type" content="blog" />`

This update is a shared view and can be found here:
\source\DasBlog.Web.UI\Views\Shared\_OpenGraphPartial.cshtml

I am creating this for community members who are interested in making an OSS contribution in a friendly environment😊

**Comment by SimplyGed** [comment]
This looks like it has already been fixed

**Comment by shanselman** [comment]
Yes fixed in #478
