### ISSUE TITLE
Html Header Author Error

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#466]
Author information is pulling out the author email rather than the author name.

**DasBlogBaseController.cs**

`ViewData["Author"] = post.Author;`

**Comment by thousandtyone** [comment]
Happy to take this up and close it if no one else is already working on this.

**Comment by barzin144** [comment]
**CreatePost** function in **BlogPostController.cs** controller uses **Identity.Name** for fill **Auther**.
 **Identity.Name** fill with **user.UserName** value in **GetUserNameAsync**.
So when I changed that to **user.DisplayName**, **Auther** field show correctly name of user that logged in.
what do you think about if I fix it by this way?

**Comment by poppastring** [comment]
Hey @barzin144 

Thanks for asking. We do not need the current signed in user, we actually need the user that submitted the post. To ensure we get that I would use the following to get the **User** object:

`User user = settings.GetUser(entry.Author);`

I think the user.DisplayName should be what we need.

Cheers!
Mark
