### ISSUE TITLE
Create/Edit a Post should allow uploading new images

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#49]
You should be able to add a new post and attach new images or files as part of the post

**Comment by mikedamay** [comment]
@poppastring If dasBlog is a useful guide then it would seem we need the rich editor operational before this issue can be addressed. Let me know if I have misunderstood, otherwise what is the plan for a FreeTextBox replacement?

**Comment by poppastring** [comment]
@mikedamay I changed the title to reflect what I meant more closely here. What we need is an upload image. What this would do in the original dasblog code is upload the image and put <img> tag in the window that pointed to the image location.

<img border="0" src="https://www.poppastring.com/blog/content/binary/New Bitmap Image.bmp">

I will also create a new issue because it is also 100% correct that we have to integrate a rich text box editor.

**Comment by mikedamay** [comment]
issue claimed
