### ISSUE TITLE
We aren't currently respecting the "no comments" flag on a single Entry.

### ISSUE THREAD

**Issue by shanselman** [poppastring/dasblog-core#499]
We aren't currently respecting the "no comments" flag on a single Entry. I think ListCommentsViewModel needs a "commentsEnabled" that gets pulled in from <Entry><AllowComments>false</AllowComments> in the "Db."

We'd need to add that to the places that we " new ListCommentsViewModel" and then include "AllowedComments" and copy it over, that would also allow one to show "Comments are Closed"  

We'd also need to add a "And AreCommentsAllowed" in CommentBlockPartial because this is only date focused:

`        @if (dasBlogSettings.AreCommentsPermitted(Model.PostDate))
`

**Comment by poppastring** [comment]
Resolved.
