### ISSUE TITLE
OpenLiveWriter integration broken?

### ISSUE THREAD

**Issue by phatcher** [poppastring/dasblog-core#507]
I can't get OpenLiveWriter to connect no matter what API integration I set - this is both locally and when deployed in Azure

**Comment by shanselman** [comment]
Do you have TLS 1.1 or 1.2?

**Comment by phatcher** [comment]
1.2

**Comment by phatcher** [comment]
That was it, works with TLS 1.1

BTW How do you do code styling etc given that OLW doesn't really support addins anymore?  Part of the reason I don't blog more is that I spend so much time sorting out hygiene factors that I don't get around to writing much.

**Comment by shanselman** [comment]
Honestly I use the PreCode plugin and the original WindowsLiveWriter.

And with the TLS thing, it's annoying but I kept it at 1.2 and then I run
fiddler locally and proxy through it. It's really ridiculous.

**Comment by phatcher** [comment]
Can easily install that version into Win 10 - fails to download some cabs from MS.

Precode provides a desktop version as well so I'll try formatting the code in that and paste from that
