### ISSUE TITLE
Build output from the YAML needs help

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#512]
I am having problem with auto deployment from the build output produced from the YAML file. I created an [issue to change the zip file name to include the build version number](https://github.com/poppastring/dasblog-core/issues/459).

This worked on the surface but the deployment does not actually work because the content of the zip file changed. The zip file appears to now include a series of unnecessary folders along with the zip file within the zip file, as follows:

```
dasblog-core_2.21.659.zip
     - a/windows-2019
     - a/DasBlog.Web.UI.zip

```

DasBlog.Web.UI.zip contains all the necessary build output.

**Comment by poppastring** [comment]
Any ideas about this? @SimplyGed

**Comment by poppastring** [comment]
cc @shanselman My deploys have failed for a while, please do not merge or deploy with the default YAML until we get this resolved. (I think you have a custom YAML anyway)

**Comment by SimplyGed** [comment]
My apologies. I didn't realise that the zip file was including all those folders.
I've issued a PR that should fix the issues and only include the correct files.

I setup my own pipeline and release in Azure to verify and the file matches the layout prior to the original zip file naming changes.

**Comment by poppastring** [comment]
@SimplyGed  No worries :) Thanks a bunch for looking at this so quickly!
