### ISSUE TITLE
Passwords always hashed with MD5

### ISSUE THREAD

**Issue by bradwyoung** [poppastring/dasblog-core#516]
Even though issue #57 was closed, the hash algorithm is explicitly set to MD5 in the HashPassword method of SiteSecurityManager. I fixed the issue and can do PR, but wanted to see if maybe I am missing something.

**Comment by poppastring** [comment]
@bradwyoung  Thanks for the question and the PR, I will take a look in the next day or so. The original intent was to be able to support existing dasblog config files and essentially upgrade them when you hit save.
  
Thanks again!
