### ISSUE TITLE
Need to add an email setting for From address

### ISSUE THREAD

**Issue by bradwyoung** [poppastring/dasblog-core#526]
The send email logic assumes the SMTP User name is an email address.  This is not always the case for SendGrid SMTP.  I don't see a way to fix this without a new setting.  

Is there an option I am missing?

**Comment by poppastring** [comment]
Hey @bradwyoung !  I do not think we have anything like that, if this is necessary please feel free to submit this change to the config file and the admin page.

Whatever change we propose should minimize the risk of breaking the existing folks who have have used this settings as is.

Thx!
