### ISSUE TITLE
Logged in successfully but Authorization Failed

### ISSUE THREAD

**Issue by rullyrmd** [poppastring/dasblog-core#538]
I tried deploy DasBlog Core on Centos 8 on Azure VM.

But the log always say like this :

![image](https://user-images.githubusercontent.com/15206988/111057257-a90d4480-84b8-11eb-9393-2dbc865e238b.png)

I tried :
1. follow guide [https://github.com/poppastring/dasblog-core/wiki/1.-Deployment](url)
2. follow guide [https://github.com/poppastring/dasblog-core/wiki/2.-Configure-your-blog](url) (stuck on step 1)
3. deploy with Development and Production Environment
4. deploy with and without nginx
5. update site.*.config Root

but result are still the same

**Comment by poppastring** [comment]
That is very strange. I could not recreate this outcome on App services for Linux:

**Comment by susilj** [comment]
Having the same issue. I am executing in my laptop. AuthorizationRoleTagHelper results in authorization failure. Trying to navigate to /post/create after successful login redirects to login page.

![image](https://user-images.githubusercontent.com/3763122/111876668-d29d0300-89c5-11eb-8245-21bac600ec9c.png)

**Comment by manzanotti** [comment]
On a possibly related issue, I can log in as admin locally (running http on port 5000) (I've stepped through it in the debugger, and I do successfully log in), but when the page redirects to the home page of the blog, the login link still shows in the nav bar.

I've tried debugging the AuthorizationRoleTagHelper, but that just runs methods on the policy evaluator, at which point my knowledge ends.

Do you think this might be related? If not, I can create a separate issue.

**Comment by rullyrmd** [comment]
@manzanotti it's exactly related issues. I have the same problem. Login is success but when the page redirects to the home page of the blog, the login link still shows in the nav bar.

**Comment by manzanotti** [comment]
I'm wondering if it's because I'm not running it with https when running locally? @poppastring Is there a policy that mandates https when logged in?

**Comment by poppastring** [comment]
Thanks for the tip @manzanotti  I can replicate this issue when I log in locally over HTTP. No idea why this is the case but at least I can replicate now.

**Comment by rullyrmd** [comment]
@manzanotti @poppastring 
Thanks for the tip too, now I can reproduce this issue on my local machine.

I try changing this line :

1. add services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
2. move some cookie options from services.ConfigureApplicationCookie to services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie

and this will fix on HTTP

how do you think?

![image](https://user-images.githubusercontent.com/15206988/113433307-274e6e00-9409-11eb-89b2-45e8067e6b10.png)

**Comment by poppastring** [comment]
@rullyrmd Excellent! Please submit a PR and I will take a look this weekend.

**Comment by rullyrmd** [comment]
PR #554 

Submitted!
