### ISSUE TITLE
Title length max is 60 chars on edit page, but OLW can create a post with a longer title.

### ISSUE THREAD

**Issue by manzanotti** [poppastring/dasblog-core#540]
I'm using Open Live Writer to post to my blog. I've just created one, then gone in to edit it using the edit page on the blog itself. I cannot save any updates, because the title length is greater than 60 characters.

I'm happy to argue that 60 characters is not long enough for a title field, so is it worth removing the limit, or increasing it substantially?

**Comment by manzanotti** [comment]
I've had a quite look through the code, and whilst I can find the edit page, I can't see how validation is applied. I'll keep looking, happy to put a PR in if I can work it out.

**Comment by manzanotti** [comment]
And as soon as I post that, I find the validation!

I guess this means that the API that OLW is posting to isn't using the same model and validation then? (I'll keep looking in the code for that).

**Comment by poppastring** [comment]
@manzanotti  Thanks for finding this! Yes lets remove the limit, especially if there is no reasonable limit associated with OLW. The OLW API (/feed/blog) simply submits a blob of XML it does not pass through the same validation.

Feel free to submit a PR if you get a chance :)

**Comment by manzanotti** [comment]
Done!

https://github.com/poppastring/dasblog-core/pull/541
