### ISSUE TITLE
Blog post images using size attributes are made bigger

### ISSUE THREAD

**Issue by manzanotti** [poppastring/dasblog-core#542]
I'm using OLW to post to my blog, and it uses the height and width html attributes on images to specify the image size.

Unfortunately, these are over-ridden by site.css, as the .dbc-post-content img rule sets the width and height to 100%

![Das Blog Image size](https://user-images.githubusercontent.com/2589151/112502444-fb384a80-8d81-11eb-8af0-f1381bfd6aa7.jpg)

I don't know if this should be a bug for the OLW project (I presume that using inline style attributes on the image would solve the issue), or whether the bug is this CSS rule; is the rule needed?

**Comment by poppastring** [comment]
@manzanotti  This CSS rule is set as part of the site.css (the broad rules applied to the site) and impacts the div associated with blog post content. In hindsight I think this should be removed from the site.css and added to each theme explicitly (in each custom.css). By doing this it is easier for everyone to create and modify their own specific themes without worrying about modifying the site theme (which gets overridden when you update).

**Comment by manzanotti** [comment]
Happy to move it into each theme. One question though: when you say that this impacts the blog post content div, how does it do that exactly? My CSS is a little rusty, I must admit, but doesn't setting the img height and width to 100% only make the image take up the space that the div has given it, rather than the image forcing the div to be a certain size?

I have set my blog to use each theme, and used dev tools to turn off that style, and other than the images, I can't see it affect anything else on the page.

I guess I'm really asking whether it is needed at all?

**Comment by poppastring** [comment]
Yes sure, I am absolutely fine with just removing it, I personally use it but I have created my own theme so it makes no difference for my specific needs. I assume if someone else wants they could include it (I have no evidence that anyone will else will need it).

**Comment by manzanotti** [comment]
I'll sort a PR out this weekend then.

Out of curiosity, and to fill a hole in my CSS knowledge, what does it do on your theme?

**Comment by poppastring** [comment]
@manzanotti  On my blog I always have an image in every post and so this automatic resizing is helpful to me. There are image scenarios where this is unhelpful (rarer for me) and in those scenarios I use inline CSS as attribute of the image tag (which overrides the predefined CSS).
For example this image goes to a maximum of 60% of the post width:
`<img **style="max-width: 60%;"** src="https://www.poppastring.com/blog/content/some-image.png" >`

Another way to do this, and probably the most flexible solution, would be to remove the default style all together from the site.css, and replace it with this:
```
.dbc-post-image-full {
    width: 100%;
    height: 100%;
} 
```
If I need this style I can apply the style to the image by using the class attribute as follows:
`<img **class="dbc-post-image-full"** src="https://www.poppastring.com/blog/content/some-image.png" >`

I hope that makes sense.

**Comment by manzanotti** [comment]
Aye, that makes perfect sense, thanks!

**Comment by manzanotti** [comment]
PR submitted:

https://github.com/poppastring/dasblog-core/pull/546

Haven't worked out how to link the issue to the PR yet, I'm guessing that it's a permissions thing?
