### ISSUE TITLE
Menu too large when window size 972px and below

### ISSUE THREAD

**Issue by manzanotti** [poppastring/dasblog-core#543]
When resizing the browser window, when it reaches a width of around 972px, the menu changes from a horizontal layout to a vertical one. This wouldn't be much of an issue, but it is also marked as sticky, so it does not move when scrolling down the page. As the menu height is set to 472px, if the height of the window anywhere near that, you cannot read any of the article.

![Das Blog Large Menu](https://user-images.githubusercontent.com/2589151/112503692-0dff4f00-8d83-11eb-8e83-250c21e0f3e1.jpg)

I suggest that the menu should be collapsed by default when at that size, so you have to click a menu icon to open up the menu options.

**Comment by poppastring** [comment]
@manzanotti I really like this idea!

**Comment by rullyrmd** [comment]
![image](https://user-images.githubusercontent.com/15206988/113440496-bf9f1f80-9416-11eb-9af5-a64dc19c17c2.png)

![image](https://user-images.githubusercontent.com/15206988/113440527-ccbc0e80-9416-11eb-8b9a-22f316a93815.png)

How about this ?
No additional CSS needed, just add toggle button and adjust some HTML class in _Layout.cshtml (Themes/darkly)

but I found some issue.

On images above I comment out line startup.cs 395 (//.CustomSources("https:"))

If not will produce error like this.

![image](https://user-images.githubusercontent.com/15206988/113441033-bb273680-9417-11eb-915b-c4d4d04977c7.png)

**Comment by poppastring** [comment]
@rullyrmd Could you submit a PR for this?
To resolve the subsequent issue with security ("refused to load") we may want to consider optionally including/excluding `.CustomSources("https:"))` based on the URI of the site.config `Root` element.

**Comment by rullyrmd** [comment]
done #561

**Comment by poppastring** [comment]
Thank you so much! @rullyrmd  Just merged your change.

@manzanotti  The update currently exists in the darkly theme, however, if you pull the changes as is it will overwrite and customizations you might have. If this is the case my suggestion is to [create your own theme (copy the existing theme folder)](https://github.com/poppastring/dasblog-core/wiki/4.-Designing-a-theme) so this does not overwrite any changes you need.

**Comment by manzanotti** [comment]
@poppastring I've not actually made any changes to the theme, so I can just pull this down.

One question, however; as all but one theme has exactly the same html structure (and the one that doesn't, Fulcrum, could actually be changed to have the same list html), is there scope to pull the menu out into a partial that is shared by all the themes, whilst still allowing an individual theme to override that? (I've been coding SPAs for the last decade, so my razor is a little, ahem, rusty).

**Comment by poppastring** [comment]
@manzanotti Yep absolutely, that is a actually a great idea!
