### ISSUE TITLE
Posts without categories cause exceptions when mapping data

### ISSUE THREAD

**Issue by manzanotti** [poppastring/dasblog-core#547]
I'm using OLW to post to my blog, so none of my posts currently have categories associated with them. When I run this locally, every blog displayed, whether on the home page or individually, causes an exception to be thrown in the AutoMapper PostProfile, as categories is null.

This must be dealt with, as it doesn't propagate to what is displayed to the user (i.e. there's no yellow screen of death), but given the performance implications of unwinding the stack, would it not be better to add some null checking to the ConvertCategory method in that profile?

I'm happy to put in a PR, if you think this is worth doing.

**Comment by poppastring** [comment]
@manzanotti This is a great catch! Please feel free to resolve this. It always amazes me what obvious bugs can go undetected for so long. Cheers!

**Comment by manzanotti** [comment]
@poppastring Been there, missed the bugs too! It's easily done, especially when you get really comfortable with a codebase.

PR #548 submitted.
