### ISSUE TITLE
Have an option to minimise comment region on home page

### ISSUE THREAD

**Issue by manzanotti** [poppastring/dasblog-core#551]
I was wondering what you thought about having an option to specify that the comments section is collapsed on the home page?

It's just that the comment section takes up a lot of space between the articles on the home page, and it struck me that it would look better if it was collapsed, maybe with an "Add Comment" button that expanded it.

Happy to look into it, if you think it's worth doing.

**Comment by poppastring** [comment]
@manzanotti 
Sure thing! 

Please bear in mind the fundamentals of themes, I try to explain some of the [fundamentals of Themes here](https://github.com/poppastring/dasblog-core/wiki/4.-Designing-a-theme). 

Part of my assumption (note sure it is correct) was that everyone would want to do something slightly different and you can accomplish this by creating your own theme (will not be overridden after an upgrade).

Also there is a concept of Summary Item which allows you to have the home/front page of the blog formatted differently to your individual post.
![image](https://user-images.githubusercontent.com/8739371/113436980-c6487b00-93b3-11eb-972d-0eb82f5e12e2.png)

So the default **darkly** theme's summary front page layout like this (look at _BlogItemSummary.cshtml for more details) but you could add a comment link that leads you directly to the comment section of the post (see [my site](https://www.poppastring.com/blog)):
![image](https://user-images.githubusercontent.com/8739371/113437152-1aebf600-93b4-11eb-9a08-e536626b0d17.png)

[I actually just saw a [bug in _BlogItemSummary.cshtml](https://github.com/poppastring/dasblog-core/issues/555) that I need to resolve]

**Comment by poppastring** [comment]
@manzanotti 

Just to bring this to a conclusion I do think that we can and should give a better layout for the front page, and it should assume you use **"Show 'Summary View' on home page"** (recently renamed). This means first updating the **_BlogItemSummary.cshtml** to match **_BlogItem.cshtml** in the darkly Theme.

As this is all based on bootstrap here is a [link to what I think of as the assumed solution](https://getbootstrap.com/docs/3.4/javascript/#collapse). This is my best guess on how we should treat the comment block associated with each post:

```
<a class="btn btn-primary" role="button" data-toggle="collapse" href="#@Model.Comments.PostId" aria-expanded="false" aria-controls="@Model.Comments.PostId">
    Add a comment
</a>

<div class="collapse" id="@Model.Comments.PostId">
    <partial name="_CommentBlockPartial" model="@Model.Comments" />
</div>
```
