### ISSUE TITLE
OLW creates new post when publishing an existing article

### ISSUE THREAD

**Issue by manzanotti** [poppastring/dasblog-core#552]
This appears to be an issue with OLW rather than Das Blog, but over the weekend, if I published an edit to an existing blog post using OLW, then a new post was created, rather than updating the previously published version.

I've had a look at the OLW code, and it does have a property on the blog client options for the Post Edit Url. Digging a bit further, I found the entry for Das Blog in a configuration file, and it looks like there's a setting of a Uri that OLW can call to, presumably, get the Uris for the blog service APIs. For Das Blog, this is pointing to /blog/blogger.aspx. I'm going to take a punt and say that is for the non-dotnet Core version of the site, is that correct?

Is there an equivalent endpoint in Das Blog Core? I haven't found anything that looks like it might be, but there's every chance that I've just missed it. Or am I barking up the wrong tree with this whole concept?

**Comment by Crypt32** [comment]
I don't think it is OLW issue. OLW properly calls `metaWeblog.newPost()` for new blog post and `metaWeblog.editPost()` for existing blog post revision. If you push an update for previously published post and new post is created -- it is DasBlog issue. I'm using WLW/OLW for 13yrs and it never behaved this way.

**Comment by poppastring** [comment]
@manzanotti 
I have never personally come across this issue so any additional info you can provide on replication would be invaluable.

To answer your question the endpoint that is used by OLW is /feed/blogger (checkout the FeedController). OLW gets that information by looking at the /feed/rsd endpoint, which is referenced as a link in the html header of the home page as follows:

`<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.somesite.com/feed/rsd">`

**Comment by manzanotti** [comment]
@poppastring Thanks for the tips, found the issue. Well, a couple of issues, I think. When I hit publish in OLW on an existing post, it does send it to the 

The first issue is to do with the lack of categories again. The Entry class Categories property has a setter that just trims the value sent through, so if that is null, then it just throws an exception. That's an easy enough fix.

The second potential issue is that this error is then turned into a string of XML in the Invoke method of the XmlRpcManager. This means that the BloggerPost method in the FeedController, which has its own try catch block around the call to that manager, thinks that the post has been successfully submitted. I can't actually see any way in which that method will think that the post hasn't been successfully processed, and, even if it does, it actually just logs an error, before then continuing on the successful post path.

I don't know if OLW should handle the XML fault that is being returned better, or if it is expecting the Http Status Code to indicate an error. Whatever the reason, it is currently interpreting what is returned as if the post doesn't exist, so it then If I comment out the exception handling code, then OWL just shows a popup with the exception message in it, and doesn't create a duplicate post.

Happy to put a PR in to fix the categories issue, but wanted to see what you thought about the error messaging situation here?

**Comment by poppastring** [comment]
@manzanotti 
I think you should go ahead fix the first issue. My concern with the second fix is that while duplication is bad, losing a post is the only thing that I can imagine being worse.

Could you please send the second fix separately and I can run a few test scenarios and confirm how we want to handle it.

Thanks!!!

**Comment by manzanotti** [comment]
First fix in #558
