### ISSUE TITLE
Fix the BlogItemSummary razor page

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#555]
Each blog item summary razor page (defined by _BlogItemSummary.cshtml) uses an `<img>`. 
This was only meant to be a place holder and we should either allow the image to point to the default image of the post (`@Model.ImageUrl.`).

Or, preferably, update the existing TagHelper for the default image of any post:
`<post-image class="card-img-right flex-auto d-none d-lg-block" style="width: 200px; height: 250px;" alt="" />`

**Comment by rullyrmd** [comment]
@poppastring I try to work on this.

![image](https://user-images.githubusercontent.com/15206988/113466484-7971ac80-9466-11eb-88b5-3ec9a0947372.png)

![image](https://user-images.githubusercontent.com/15206988/113466497-9c9c5c00-9466-11eb-861a-92d5ad076f94.png)

1. [Add] new Class : TagHelper/Post/PostImageLinkTagHelper.cs
2. [Update] Themes/darkly/_BlogItemSummary.cshtml

Result :

![image](https://user-images.githubusercontent.com/15206988/113466510-bb025780-9466-11eb-9a53-f36e76e1ea08.png)

How do you think?
I'm happy to resolve this and put in a PR.

**Comment by poppastring** [comment]
My apologies @rullyrmd I made an error here in that there is an existing tag helper that needs to be updated called PostImageTagHelper.

What still needs to happen is that we should add two new public properties (**Class**, **Style**) that represent the `class` and the `style `associated with the image. The _ProcessAsync_ method will include this:
`option.Attribute.SetAttribute("class", Class);`
`option.Attribute.SetAttribute("style", Style);`

Also an additional public property called **DefaultImage** which will allow us to have a default image if the blog post does not actually have an image (is null or empty) then we use the _DefaultImage_.

`option.Attribute.SetAttribute("href", DefaultImage);`


Hope that makes sense. My apologies for the confusion.

**Comment by rullyrmd** [comment]
@poppastring Got it!

Updated :

**1. PostImageTagHelper.cs**

```

//3 new public properties
public string DefaultImage { get; set; }
public string Class { get; set; }
public string Style { get; set; }

//updated Process method
public override void Process(TagHelperContext context, TagHelperOutput output)
{
	var imgUrl = Post.ImageUrl;

	output.TagMode = TagMode.SelfClosing;
	output.TagName = "img";

	if (!string.IsNullOrEmpty(imgUrl))
	{
		output.Attributes.SetAttribute("src", dasBlogSettings.RelativeToRoot(imgUrl));
	}
	else
	{
		output.Attributes.SetAttribute("src", DefaultImage);
	}

	if (!string.IsNullOrEmpty(Class))
	{
		output.Attributes.SetAttribute("class", Class);
	}

	if (!string.IsNullOrEmpty(Style))
	{
		output.Attributes.SetAttribute("style", Style);
	}
}
```

**2. _BlogItemSummary.cshtml**

```
//updated image tag helper
<post-image post=@Model class="card-img-right flex-auto d-none d-lg-block" style="width: 200px; height: 250px;" default-image="https://github.com/poppastring/dasblog-core/raw/main/images/dasblog.jpg" />
```

Result :

![image](https://user-images.githubusercontent.com/15206988/113512133-77eed400-958d-11eb-8cae-ca60d45d1279.png)


If this OK, I will put in a PR.

**Comment by poppastring** [comment]
@rullyrmd Looks great, many thanks!!!
