### ISSUE TITLE
"Enable comment days limitation" - Setting Not Honored

### ISSUE THREAD

**Issue by thousandtyone** [poppastring/dasblog-core#567]
Requirement: As a blogger, I want to enable comments for all my blog post no matter how old they are.

Steps to reproduce the issue:

1.  Login  to the blog and go to site admin section.
2. Disable "Enable comment days limitation"
3. Leave the number of days value as 1 (since 0 is not allowed).
4. The final setting looks like:
![image](https://user-images.githubusercontent.com/24845706/122815582-44e9f000-d2f3-11eb-9981-388e2fab60c5.png)

5. However, when I log out and as a user I try to submit a comment, I get a message stating that comments are closed.
![image](https://user-images.githubusercontent.com/24845706/122815863-a3af6980-d2f3-11eb-812e-18b818c3e978.png)

Expected Behavior:
Since I've disabled comment days limitation - my comments should never be closed. Looks like the system is still taking the number of days passed in the textbox and honoring that.

If this is accepted as a bug, I'll be happy to take a look at it and submit a PR for the fix if needed.

**Comment by poppastring** [comment]
Thanks for finding this @thousandtyone

**Comment by thousandtyone** [comment]
Done. PR submitted. Please feel free to review and let me know if any added changes are needed for this and I'll be happy to make them.
