### ISSUE TITLE
Possibility Of Including A Clean Minimalist Simple Archive Listing?

### ISSUE THREAD

**Issue by thousandtyone** [poppastring/dasblog-core#568]
In the older version of DasBlog I had developed a simple, clean minimalist version of achieve listing by date.

A Sample Deployment is available here:
https://www.thousandtyone.com/blog/archivelisting.aspx

While I am working on moving my blog to this version, this seems to be the only missing piece now left to be able to port over. I could develop this independently, but then I need to maintain and build this code locally and merge it every time I do a pull. 

Is there interested in having a simple, minimalistic archive listing like this one? If yes, I would be happy to implement this as a DasBlog feature where users have support for different styles of achieve and can choose whichever style of archiving works best for them?

If this helps, this issue can be converted into an enhancement and I can take it up and submit a PR. However, if it appears like this will be additional bloat and will not help the product, I can totally understand.

Please do let me know what you think.

**Comment by poppastring** [comment]
My initial thoughts are that we should be flexible enough to allow for this scenario, I am thinking something like `/archive/all` or `archive/list`. We would have a default view that anybody can overwrite in there own custom theme. I would like to solicit some feedback before we commit though.

@shanselman  Any thoughts here?

**Comment by poppastring** [comment]
@thousandtyone This has been completed

**Comment by thousandtyone** [comment]
Thanks! I think this is all I needed to move my live blog over to this version. Thanks so much for this!
