### ISSUE TITLE
Comment Button is still Shown and fails without error when Comments are Disabled in the site settings.

### ISSUE THREAD

**Issue by thousandtyone** [poppastring/dasblog-core#570]
As a blogger, when I disable comments on the blog, my users / readers should not even see the comment button on the site OR if the button is visible a proper error message must be displayed. Right the users see a button but when they try to comment nothing happens.

Steps to reproduce:

Disable comments completely on the site.

![image](https://user-images.githubusercontent.com/24845706/123156806-5e23a580-d487-11eb-9627-3488b827bd83.png)

Navigate to the home page. The comment button is still visible by default:
![image](https://user-images.githubusercontent.com/24845706/123157612-629c8e00-d488-11eb-9eac-df81513a045a.png)

Clicking on the "Add a comment" button does nothing though and no errors are displayed. The readers are not told that comments are disabled.

Not sure if this is expected behavior but just like the users are informed the comments are locked when they are locked, in this case the users should be told that comments are disabled on this site. Or some relevant message should be displayed to that they don't end up feeling like the comments aren't working when they are in fact disabled on purpose by the author.

Expected Behavior: Either don't show the comment button or report a valid error when users try to use it when commenting is disabled in the site settings.

Reporting here since this looks like a bug. Feel free to assign to me if it is indeed a bug, and I'll be happy to submit the PR for this.

**Comment by poppastring** [comment]
@thousandtyone Great find!

**Comment by rumdood** [comment]
@thousandtyone do you have any issues with me submitting a PR for this?

**Comment by thousandtyone** [comment]
@rumdood - Thanks so much for closing this. Apologies could not respond earlier.
