### ISSUE TITLE
"dasblog-core init" fails in .NET 6

### ISSUE THREAD

**Issue by rumdood** [poppastring/dasblog-core#589]
Tried manually publishing the app to a new app service. Set the stack to .NET/.NET6 (Early Access), went to the KEDA debug console and attempted to run `dasblog-core init` and got an error that the .NET6 runtime couldn't be found despite the fact that I was able to browse to the website (though since uninitialized it has localhost for all its links).

![image](https://user-images.githubusercontent.com/3585996/141935883-a138ed0a-9350-4f4b-b840-c7a1f50fdc48.png)

Attempted to do this on my local environment with .NET 6 installed (6.0.100). Built Dasblog.Web.UI, published it, and then went to the output folder to run dasblog-core init and got the same result.

![image](https://user-images.githubusercontent.com/3585996/142030599-5b31e0d6-2275-45c3-a89d-863a4e357444.png)

I suspect this is an issue with the dasblog.cli project. I noted in the project that it references a dasblog-core.runtimeconfig.json that points to netcoreapp3.1 and AspNetCore.App 3.1.0 while the project is 6.0:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    }
  }
}
```

I'm happy to poke around at this to see if I can get it fixed. Ran out of time last night.

**Comment by poppastring** [comment]
@rumdood  Thanks for the thorough investigation! I have not tested that component since the upgrade. I can take a look at this one tonight. Cheers!
