### ISSUE TITLE
Create a Share to LinkedIn TagHelper

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#606]
Create a new taghelper for sharing to LinkedIn. There are several examples in the `TagHelpers/Post` (e.g. Facebook, Twitter).

`https://www.linkedin.com/sharing/share-offsite/?url={url}`

**Comment by zukomgwili** [comment]
Good day @poppastring. I would like to take this issue on if it has not been assigned to anyone else.

**Comment by poppastring** [comment]
@zukomgwili Thank you so much! Please feel free to send a PR when you are done or even if you just need feedback.

**Comment by zukomgwili** [comment]
@poppastring Thank you for the opportunity to contribute; much appreciated.

**Comment by poppastring** [comment]
closed by #609
