### ISSUE TITLE
Throw exception in c# 10 way

### ISSUE THREAD

**Issue by musmanrafiq** [poppastring/dasblog-core#611]
Instead of check for null and then throwing exception we can do both in single line in c# 10

Example :
// let say we have a variable abc
// we want to throw exception in case if its null

Old Way:

          if (abc == null)
          {
               throw new ArgumentNullException("abc");
           }

New Way:

           // in c# 10 we can do it in this way
           ArgumentNullException.ThrowIfNull(abc, nameof(abc));

**Comment by musmanrafiq** [comment]
Created pull request for that : https://github.com/poppastring/dasblog-core/pull/612

**Comment by poppastring** [comment]
@musmanrafiq I agree this is a much better syntax but I am only willing to do this if there is considerable benefit over the previous method.
