### ISSUE TITLE
BaseURL needs to be removed

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#637]
We set the PathBase for the site which is problematic depending on which location you host from. 

`context.Request.PathBase = new PathString(path);`

We should rely on ASP.NET to resolve this for us by default. This is only absolutely required for things like RSS.

**Comment by poppastring** [comment]
Resolved in v8

**Comment by shanselman** [comment]
I definitely need to test this because I'm behind FrontDoor
https://www.hanselman.com/blog/dealing-with-application-base-urls-and-razor-link-generation-while-hosting-aspnet-web-apps-behind-reverse-proxies
