### ISSUE TITLE
Increase the time for posts on Front Page

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#640]
Front page day count should support 10,000 days.

![image](https://user-images.githubusercontent.com/8739371/177057590-a96e0aaf-3baf-4dcc-88be-0b606fa2a363.png)

**Comment by lodenrogue** [comment]
10,000 days is 27 years.

**Comment by poppastring** [comment]
> 10,000 days is 27 years.

@lodenrogue Yep! 
I actually want it to be a very long time, as in permanent. That way I could have a front page from a specific category that always sticks to the front page of the blog.

Alternatively, we could have a value that represents forever, maybe "-1" or something. Thoughts?

**Comment by lodenrogue** [comment]
10,000 should work for that. I'm opening a PR now with the changes

**Comment by lodenrogue** [comment]
PR: https://github.com/poppastring/dasblog-core/pull/641

**Comment by poppastring** [comment]
Thanks @lodenrogue 

#641
