### ISSUE TITLE
Login to running instance in development environment ist mpossible

### ISSUE THREAD

**Issue by twoelfer** [poppastring/dasblog-core#643]
Hi.

I have pulled the source, opened the solution in vs 2022, rebuild, and started in the debugger. when i try to log in using 'myemail@myemail.com' and 'admin', edge is only displaying an error window, telling me the connection is insecure. i cannot do anything more: there doesn't seem to be a way to ignore this "problem". How can i run this in the debugger, when installed locally?

WM_THX
-thomas woelfer

**Comment by poppastring** [comment]
@twoelfer 

By default local development assumes you are using a localhost dev cert with https. If you need to develop without a cert (over http) then start by updating the _site.Development.config_ as follows:

`<Root>http://localhost:5000/</Root>`

When you start debugging (the page will probably look broken) and navigate to `http://localhost:5000/account/login` and attempt to login. 

If this still fails, please let me know.

**Comment by twoelfer** [comment]
@poppastring 
Mark, i do have a standard vs 2022 setup. The dev certs are installed, i just verified with 

>> C:\Program Files\Microsoft Visual Studio\2022\Professional>dotnet dev-certs https
>> A valid HTTPS certificate is already present.

So basically, i should just work, shouldn't it? Or do i need to set up something inside the solution for debugging? my own website projects simply work over https on both my dev machines, and i don't think i ever configured something for that... so i'm not sure where to look. Any ideas?

**Comment by poppastring** [comment]
@twoelfer 

Yep, that is strange, it should just work. Can you try using Kestral rather than IIS?

![image](https://user-images.githubusercontent.com/8739371/180669027-3ccb39c7-6e00-4cec-9a15-d7fec4e109d0.png)

If you look at the Debug Properties (note the app url should match the root, site.config):
![image](https://user-images.githubusercontent.com/8739371/180669200-a6b4979a-1f80-4d10-a027-a8286039a4aa.png)

**Comment by twoelfer** [comment]
So this works. Strange. However, i get to look at the code in the debugger. That's what i need to get me started...
