### ISSUE TITLE
What needs to be done incase multiple blogs are needed?

### ISSUE THREAD

**Issue by twoelfer** [poppastring/dasblog-core#644]
I understand, dasblog currently only supports one user. However, i do need several blogs on my server. (3 actually: blogs.die.de/tw, blogs.die.de/aw and blogs.die.de/cm ) [i'm currently using blogengine.net, which does support multiple blogs, but doesn't have a .net core version.]

Any suggestions how i could set it up like this?

WM_THX
-thomas woelfer

**Comment by poppastring** [comment]
Yes, dasblog only supports one user but it was always my intent to [support multiple users (added an issue for that)](https://github.com/poppastring/dasblog-core/issues/645).

I believe you can support that scenario you are describing. For example, I currently have my blog hosted on Azure, I placed my blog in a sub folder "poppastring.com/blog".  I assume I could also add another sub folder and install dasblog there, also for example, poppastring.com/info and deploy.

Does your web host support sub applications/folders?

**Comment by twoelfer** [comment]
@poppastring 
Mark, i'm also hosted on azure. Are you saying you would just run 3 instances of dasblog in separate subdirectories? i'm not sure azure supports this. i can try though - however, i was under the impression, it's more an 'one-webapp-per-website' kind of setup that we can build in azure. So i was hoping for "multiple endpoints" in dasblog. Also, this way, i would have 3 instances of dasblog running, which is not so good from a resource consumption pov and, of course, not easily managed...

Anyway: I will try to do this.

**Comment by poppastring** [comment]
@twoelfer 

So I got two instances of dasblog working under App Services for Window:
- https://buggy-demo-code.azurewebsites.net/
- https://buggy-demo-code.azurewebsites.net/tw

I had to create a new virtual directory for the additional dasblog deployment:
![image](https://user-images.githubusercontent.com/8739371/180667941-d27489e1-1973-46a9-85cb-d9b80c21f5da.png)

On the second instance I had to change the web.config as follows:
![image](https://user-images.githubusercontent.com/8739371/180668048-6485e9a3-db4f-4c56-bfb1-e02539449ed1.png)

...and also the associated config files.

I hope this helps!

**Comment by twoelfer** [comment]
Thank you!
