### ISSUE TITLE
Markdown powered comments 

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#659]
Comments currently allow specific html tags, governed by a combination of the site.config and custom code.
![image](https://user-images.githubusercontent.com/8739371/204938066-78609de3-b6a2-4796-b734-a6c0f8afad0e.png)

Let's simplify comments code by accepting Markdown. The MD entry will be converted to HTML by using the [MarkDig plugin](https://www.nuget.org/packages/Markdig).

**Comment by trekmeup** [comment]
I am happy to take a stab at this if no-one else is working on this. I love the idea of supporting markdown and if this works, would we be open to the idea of also allowing markdown for posts? We can start with comments and see how it goes.

**Comment by thousandtyone** [comment]
I am happy to take a stab at this if no-one else is working on this. I love the idea of supporting markdown and if this works, would we be open to the idea of also allowing markdown for posts? We can start with comments and see how it goes. Okay to take a quick attempt at this if no-one else is working on this?

I can try and submit a PR in a couple of weeks.

**Comment by poppastring** [comment]
@thousandtyone Thanks!

**Comment by thousandtyone** [comment]
I've started working on this and have a quick question. Today the HTML tags allowed are limited. By introducing markdown are we completely removing the limit on markdown options allowed. For example in my comment can I type "# Hello" and the converted HTML will convert it into <h1>Hello</h1> - or do we also wanted users to use a restricted set of mark down options like allowing just bold, italics etc.? When we talk of simplifying the code I am thinking we want to remove all restrictions and allow everything in comments that markdown allows (Even if it means users can now inject H1 and H2 headers using markdown). Is this understanding correct?

**Comment by poppastring** [comment]
@thousandtyone I wanted this to be option 2. Thanks for the checking!

**Comment by poppastring** [comment]
#664
