### ISSUE TITLE
Create/Edit a Post should allow a specific language

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#67]
Create a list of valid cultures from which the user can select.
Default to the language/culture of the server.

**Comment by mikedamay** [comment]
claimed

**Comment by mikedamay** [comment]
feature available for PR once #110 has been dealt with

**Comment by mikedamay** [comment]
@poppastring 
Is there anything outstanding on this issue for me?

**Comment by poppastring** [comment]
@mikedamay No. I missed this one.
