### ISSUE TITLE
Need to enhance documentation for blog deployment options.

### ISSUE THREAD

**Issue by noopman** [poppastring/dasblog-core#679]
I have added documentation in [my project fork wiki](https://github.com/noopman/dasblog-core/wiki/1.-Deployment) about various deployment options.

The enhancement now includes the deployment option to host a dasblog-core application as a virtual application in a larger site.

Is there a better way to contribute to a GH wiki than this? If you like my changes you can add the remote [https://github.com/noopman/dasblog-core.wiki.git](https://github.com/noopman/dasblog-core.wiki.git), pull my changes and merge them into your wiki!

**Comment by noopman** [comment]
I have also added documentation for CDN. @poppastring if you pull my wiki to your local machine you can compare it to your own wiki.

[https://github.com/noopman/dasblog-core.wiki.git](https://github.com/noopman/dasblog-core.wiki.git) => [https://github.com/poppastring/dasblog-core.wiki.git](https://github.com/poppastring/dasblog-core.wiki.git). When you are satisfied you can merge my changes into your blog wiki and push it to your docs!

**Comment by poppastring** [comment]
@noopman I took an extended break to recharge, and so I am just reviewing now. Unfortunately these links 404 now, I am not sure if this info is still available. Totally understand if this is no longer available.

**Comment by noopman** [comment]
Odd. I will take a look.

**Comment by noopman** [comment]
Not sure what exactly happened here above. This is the wiki version I have [https://github.com/noopman/dasblog-core/wiki](https://github.com/noopman/dasblog-core/wiki). That page has a link to "Clone this wiki locally": [https://github.com/noopman/dasblog-core.wiki.git](https://github.com/noopman/dasblog-core.wiki.git). I am able to clone this wiki. It should be the "simple" (read: git simple) act of pulling my changes and merging them with your wiki, right? At least that is to my understanding.

One more thing - should we add some text about migrating a dasblog to (or from) using a CDN solution?

**Comment by poppastring** [comment]
@noopman Thanks a bunch, I did a little editing, and I am happy with what we have. 👍🏿 

Closing this issue.

**Comment by noopman** [comment]
I'm glad this way of contributing to the docs works! Strange that the wiki-repo is so different compared to other repos. But this way it is doable anyway.
