### ISSUE TITLE
Themes folder is hard coded as "theme" in DasBlogSettings causing custom themes css and shortcuticons to 404

### ISSUE THREAD

**Issue by klabranche** [poppastring/dasblog-core#684]
I was working on my personal theme and added to my themes layout page the `_HtmlThemPartial` to bring in my themes css.  When my css wasn't applied, Dev Tools showed 404 for "theme/mythemename/custom.css" instead of themes.  Tracked it down to the `DasBlogSettings` class and it's `ThemeCssUrl` property.  Also noticed the `ShortCutIconUrl` has the same issue.

**Comment by poppastring** [comment]
Thanks for submitting the issue, and the PR @klabranche. I am investigating this a bit further to confirm.

**Comment by poppastring** [comment]
Interesting, the request path should be valid for "/theme" or "/themes" based on how it is configured in Startup.cs.

```
app.UseStaticFiles(new StaticFileOptions
{
	FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "Themes")),
	RequestPath = "/theme",
	OnPrepareResponse = cacheControlPrepResponse
});

app.UseStaticFiles(new StaticFileOptions
{
	FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "Themes")),
	RequestPath = "/themes",
	OnPrepareResponse = cacheControlPrepResponse
});
```

So in my deployment the following both point to the same css file in my "fruit" theme:
- https://www.poppastring.com/blog/themes/fruit/custom.css
- https://www.poppastring.com/blog/theme/fruit/custom.css

@klabranche Have you deployed this? Could you confirm your full URIs for the custom.css file?

**Comment by klabranche** [comment]
@poppastring - Well, interesting, I had in fact seen it occurring on my local iis deployment and did the PR after seeing my code change fixed it.  Funny thing is, now I can't repro it even starting from scratch.  

My apologies for wasting your time, please close.

**Comment by klabranche** [comment]
Closing, can't repro.

**Comment by klabranche** [comment]
Closing, can't repro.
