### ISSUE TITLE
dasblog-core init Fails

### ISSUE THREAD

**Issue by knarfalingus** [poppastring/dasblog-core#694]
Similar to issue #589, installing manually, I ran dasblog-core.exe init and got the error

Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

I downloaded the source, in the DasBlog.CLI project I changed dasblog-core.runtimeconfig.json to be

{
  "runtimeOptions": {
    "tfm": "net8.0",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "8.0.0"
    }
  }
}

built it, replaced the binaries and it seemed to work.  Machine is a relatively new build so I do not have .NET 6 installed.

**Comment by pamanes** [comment]
Getting the same issue:

**dotnet --list-sdks**
8.0.100 [C:\Program Files\dotnet\sdk]

**dotnet --list-runtimes**
Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by poppastring** [comment]
Thanks for reporting! Sorry for the late response. Tracking this down soon.

**Comment by poppastring** [comment]
Thanks for the feedback! I have released a new update.
