### ISSUE TITLE
Cannot start the site after init

### ISSUE THREAD

**Issue by pamanes** [poppastring/dasblog-core#695]
hi, I downloaded the latest release 8.0.1194, and fixed the CLI according to this: https://github.com/poppastring/dasblog-core/issues/694

and I get the following for both the site and the root page:
![image](https://github.com/poppastring/dasblog-core/assets/1147472/ccf9c7ed-f150-4b61-87e5-6dc057bf0255)

I appreciate your help,

**Comment by poppastring** [comment]
Thanks for reporting! Sorry for the late response. Tracking this down soon.

**Comment by poppastring** [comment]
Thanks for the feedback! I have released a new update. 👍🏿
