### ISSUE TITLE
Post comment link - TagHelper

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#7]
We need a TagHelper that shows an comment link for a given blog post. The TagHelper would be exclusively for the [_PostPartial.cshtml](https://github.com/poppastring/dasblog-core/blob/master/source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml) and would be in the following format:

`<postcomment post=@Model>Comment on this post</postcomment>`

Which would produce an output like this:

`<a href="//www.baseurl.com/blog/somepost/comment">Comment on this post</a>`

TagHelpers should be created in the [DasBlog.Web.UI project](https://github.com/poppastring/dasblog-core/tree/master/source/DasBlog.Web.UI) under the TagHelpers folder, I have a [blog post on authoring TagHelpers](https://www.poppastring.com/blog/CreatingTagHelpersWithCoreMVC.aspx) here. Find out about [why we use TagHelpers here](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro), and [specific steps on authoring TagHelpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring) can be found here.

_Please note that these tasks are for code newbies who are looking to make contributions to supportive open source project using ASP.NET Core MVC. Please feel free to reach out to me on [twitter](https://twitter.com/poppastring) and I will be happy to help walk you through this._

**Comment by chillryan** [comment]
should be marked as close via #32

**Comment by poppastring** [comment]
@chillryan You fixed the edit link issue (#6) and I have closed that, this taghelper issue is for a comment link.

**Comment by chillryan** [comment]
@poppastring my PR contained the both the edit and comment tag helper. See [here](https://github.com/chillryan/dasblog-core/commit/e263304e2a7b9ef29e95b944fcee38291944db29)

**Comment by poppastring** [comment]
This was closed by @chillryan
