### ISSUE TITLE
Support the following Url format options

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#76]
\this-is-a-post (this is the current default)
or
\20180604\this-is-a-post

**Comment by Crypt32** [comment]
`+` signs should be used only for compatibility with previous DasBlog installations. Dashes should be preferred for new installations.

**Comment by mikedamay** [comment]
@poppastring legacy dasBlog suffers from the problem that if 2 entries have the same title then clicking on the title of the first post takes you to the second post -i.e. it cannot distinguish between them.  The day/title url makes it feasible to handle this by rejecting duplicates when they are created but a title only url would render uniqueness validation impractical.  Please advise

**Comment by mikedamay** [comment]
@poppastring legacy dasBlog suffers from the problem that if 2 entries have the same title then clicking on the title of the first post takes you to the second post -i.e. it cannot distinguish between them. The day/title url makes it feasible to handle this by rejecting duplicates when they are created but a title only url would render uniqueness validation impractical. Please advise

**Comment by poppastring** [comment]
@mikedamay I would like to make the "day/title" combo to be optional, this was the case with legacy dasblog (although I do not know anyone who used it) and was connected to the EnableTitlePermaLinkUnique value in the Site.Config.

When set to true we reject duplicates as you noted, false works would technically allow duplicates.


Thanks!

**Comment by mikedamay** [comment]
claimed

**Comment by mikedamay** [comment]
PR ready, subject to rebase of o/s PR

**Comment by poppastring** [comment]
Forgot this was closed :)
