### ISSUE TITLE
Implementing logging

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#81]
Audit posts
Audit login success/failure

**Comment by mikedamay** [comment]
claimed

**Comment by mikedamay** [comment]
@poppastring a couple of issues arise on logging.
1. Legacy code uses an Impersonation api not supported in core.  A lightweight change is to simply remove it.  See my feature/logging branch 2nd commit.  If I understand the issue correctly I don't think impersonation is rather inconvenient in the absence of some sort of single sign on mechanism.
2. The logging mechanism is not very extensible without touching legacy code - see EventMessageTemplates and EventCodes, e.g. to add logging for user admin.

**Comment by mikedamay** [comment]
Ready to submit PR.  Subject to review of and rebase from feature/user-admin

@poppastring I'm still not quite on the same page regarding using the title for links and confused further by permalinks.  (I have used kebab cased titles as permalinks in the log).

My problem with using the title is that if I have a post on Jan 1st 2020 called "Welcome to the Decade" and the same again on Jan 1st 2030 then which one would the link "myblog.com/welcome-to-the-decade" point to?

For external permalinks (which the log effectively has), changing the title of a post would either invalidate the permalink or if we preseved the the original title as say the entry id then having a url containing an out of date title might be more confusing than a guid.

Let me know what you think

**Comment by poppastring** [comment]
Sorry I did not see the comments here. I actually want to abandon the legacy version of logging in it entirety. This is one of the features I mention to abandon in the ReadMe.md. (kind of a core tenant thing).

**Comment by poppastring** [comment]
WRT to permalinks:-
I think the only approach is to reject and new Titles that result in the same URIs if we are not using date in the URI.

There

**Comment by mikedamay** [comment]
@poppastring 
WRT Logging
I took "Port the custom logging solution to use .NET Core" to mean in some way making the current implementation run under .NET Core.  Never mind.
Do you still want some variant of the Activity report?

**Comment by mikedamay** [comment]
@poppastring I take the point you make on permalinks.  I am not sure how it had escaped me that if it is possible to locate a post then why there should be any difficulty validating the existence of duplicates.  I will leave my other question regarding the permanence of permalinks to perhaps a consolidated discussion at some stage.  I think the implementation is in line with the requirements at present.

**Comment by mikedamay** [comment]
logging still claimed

**Comment by mikedamay** [comment]
@poppastring Is is ok to move DasBlog.Core and DasBlog.Managers from netstandard2.0 to netappcore2.1?  I can't see any disadvantages as the assemblies are unlikely to be used in any project other than DasBlog.Web.  A move has the advantage of promoting consistency and prevents annoyance when moving code between projects.  Not a show stopper but it would be good to do.

**Comment by poppastring** [comment]
@mikedamay Changing those projects is fine, best I can remember the decision to use .net standard was arbitrary. I think you may have to make a couple of subtle changes to support it, I may have tried in the past and quit after meeting some minimal resistance. I am all for consistency. Thanks!
