### ISSUE TITLE
Daily email summary

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#82]
In dasBlog's former life we would get an email summary of the activity. We should ressurect this feature.

If there is an easy to use nuget package that would be fine too. Would like to consider using [MimeKit](https://www.nuget.org/packages/MimeKit)

[Removed existing comments as I have changed the approach]

**Comment by mikedamay** [comment]
@poppastring How can I provoke legacy dasBlog into sending me an e-mail?

**Comment by poppastring** [comment]
@mikedamay 

Emailing is one of those legacy features that I am happy to abandon in legacy code and recreate.  This should lead us to completely dereference the email related project (Lesnikowski.Pawel.Mail.Pop3) for any of the more reputable and flexible Email Nuget packages.

The [legacy code appeared to send daily emails out based on a background thread](https://github.com/poppastring/dasblog/blob/master/source/newtelligence.DasBlog.Web/Global.asax.cs). I was hoping to [take advantage of Background Tasks in ASP.NET core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1) to do something similar.

**Comment by nevbartos** [comment]
@poppastring - I have made a lot of progress on this but I have a few questions about this - I've pinged you on linked in to connect.

Thanks!

**Comment by poppastring** [comment]
Starting this over...
