### ISSUE TITLE
Post Twitter share link - TagHelper

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#9]
A TagHelper that shares a Tweet for a blog post. The TagHelper would be exclusively for the [_PostPartial.cshtml](https://github.com/poppastring/dasblog-core/blob/master/source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml) and would be in the following format:

`<posttweet post=@Model>Twitter</posttweet>`

Which would produce an output like this:

`<a href="https://twitter.com/intent/tweet?url=https%3a%2f%2fwww.baseurl.com%2fblog%2fsomepost&amp;text=Some+blog+post%3f &amp;via=poppastring+%23musings" class="">Twitter</a>`

TagHelpers should be created in the [DasBlog.Web project](https://github.com/poppastring/dasblog-core/tree/master/source/DasBlog.Web.UI) under the TagHelpers folder, I have a [blog post on authoring TagHelpers](https://www.poppastring.com/blog/CreatingTagHelpersWithCoreMVC.aspx) here. Find out about [why we use TagHelpers here](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro), and [specific steps on authoring TagHelpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring) can be found here.

_Please note that these tasks are for code newbies who are looking to make contributions to supportive open source project using ASP.NET Core MVC. Please feel free to reach out to me on [twitter](https://twitter.com/poppastring) and I will be happy to help walk you through this._

**Comment by t3dodson** [comment]
Would it be ok to add an xunit project for testing the tag helpers?

I don't see an existing test project for `DasBlog.Web.UI`

**Comment by poppastring** [comment]
That would be a great help! As long as xUnit is .NET compatible, my long term goal is to ensure that we can build this anywhere .NET core can be built (Mac, Linux, etc.).

**Comment by t3dodson** [comment]
I think both `mstest` and `xunit` are both fully supported by .net core. (I have templates for both installed by default on my mac)

Here is some documentation on the [differences in the api](https://xunit.github.io/docs/comparisons.html)

**Comment by t3dodson** [comment]
I have some suggestions after reading through the [twitter api](https://dev.twitter.com/web/tweet-button/web-intent).

I see the `via` parameter is intended for the twitter username of the author. More data is needed for [the model](https://github.com/poppastring/dasblog-core/blob/master/source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs).
Perhaps the `Author` property on the model could be expanded `{ Name: string, Twitter: string }`

There is also a `hashtags` parameter which I think would map nicely to the Categories property on the model. Is that property a standard format like a csv of the categories a post is tagged with?

**Comment by poppastring** [comment]
@t3dodson ,

Currently if you want the Twitter details you can pull it via dependency injection (IDasBlogSettings.IMetaTags) . I do like the idea about expanding author model but it would mean we have to change the underlying Author type and the way it is all stored in the security file. For now take it from IMetaTags and open a new issue for changing Author, one of my guiding principles is making sure current dasBlogs owners can move easily to this new platform, so I want to give that some more thought.

Categories are semi-colon separated.

Thanks Tom!

**Comment by poppastring** [comment]
@t3dodson 

With regards to the unit testing project, I think your first suggestion, Xunit, is a good fit. Go for it!
