### ISSUE TITLE
Create an Admin page

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#92]
At minimum we should be able to update the existing admin 
- change email, displayname, password and username

[There are problems to solve around serialization/deserialization in .net core i.e. reading two records from an xml file]

**Comment by mikedamay** [comment]
What is the equivalent of this in legacy dasBlog - Settings?  Or is this just for the local user?

**Comment by poppastring** [comment]
@mikedamay This is related to siteSecurity.config, which the .net core ties into ISiteSecurityConfig.

**Comment by mikedamay** [comment]
claimed
