### ISSUE TITLE
Redesign templating system around Razor Pages

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#96]
We want the themes folder each subfolder represents a self contained theme which at minimum should be defined as follows:-
- **"Main Layout"** - Layout of the site, header definitions, can display a list of posts, or a single post.
- **"Post List page"** - This page embeds within the "Main Layout" and is able to define the layout of one more posts. Should allow us to get inventive with how the initial page is drawn.
- **"Post page"** - Defines the layout of a single blog post, includes title, body, comment section, etc.
- **_theme.css_ + _theme.js_** - Contain theme specific style and JavaScript (each "Main Layout" will have this hardcoded)

All the other components and partial pages that go into making the theme work should be placed in the shared folder system or in the wwwroot/css folder. These other components should be considered part of the dasblog-core framework and not require alteration outside of CSS and JS.

**Comment by poppastring** [comment]
@chillryan This was my high level recommendation on defining our templating, feel free to suggest changes.

**Comment by chillryan** [comment]
I pretty much agree with everything that's here. Should something change, I'll add to this issue.

**Comment by chillryan** [comment]
Wow... has it been 24 days 😳 I'll be back on this...promise!

**Comment by poppastring** [comment]
Yes definitely, go for it! Will open an issue.

**Comment by mikedamay** [comment]
I'm not sure what the ambition and technical issues are with this but I have seen a couple of projects in passing which may contribute to your thinking:
https://github.com/toddams/RazorLight
https://github.com/nopSolutions/nopCommerce
I have spent an hour or so on nopCommerce and it seems very well designed.  Have a poke around the App.Web.Framework project
