### ISSUE TITLE
Enable App to be Served Up Without IIS Express

### ISSUE THREAD

**Issue by mikedamay** [poppastring/dasblog-core#99]
Currently, it is not possible to run the app under Kestrel without change to config files.  Kestrel listens on port 50432 whereas the app has an expectation that pages are available on 50431.  

_Layout.cshtml has two elements: 
&lt;link rel="canonical" href="@ViewData["Canonical"]" />
and
&lt;base href="@dasBlogSettings.SiteConfiguration.Root" />
which tie the links to the configured 50431.

Running under Kestrel is desirable for investigating http issues.

**Comment by mikedamay** [comment]
@poppastring  Ready to submit PR.  My inexperience may show but PRs appear to include commits unconnected with the branch (in my case commits from feature/unpublished-posts is included with feature/run-without-iis-express).  So I am waiting for the previous PR to be dealt with before submitting this one.  Am I doing something wrong?  Please advise.

**Comment by poppastring** [comment]
@mikedamay So you should always create your latest feature branches from your main branche, and simultaneously ensure that your main branch is up to date with my upstream branch. This way you can have multiple feature branches that are in lock step with the main repo and ready for commitment independent of an PRs you have waiting.

As it is I suggest that you ensure that your main repo https://github.com/mikedamay/dasblog-core and create a new feature branch that solves this IIS Express/Kestrel issue, and transfer your changes to it and send the PR. It will be my job to makes sure there are no problems with each PR.

btw, I have responded to your original PR. Please let me know if my comments makes sense.
